### ISSUE TITLE
Does Multiaddr Support ip4 and ip6 in same string?

### ISSUE THREAD

**Issue by SaulMoonves** [multiformats/multiaddr#119]
Is it possible to encode something like:

/ip4/127.0.0.1/ip6/::1 to indicate that the two addresses go to the same place? Or is this invalid syntax?

**Comment by marten-seemann** [comment]
An address like that doesn't make sense. 127.0.0.1 is an IPv4 address, you can't access it on IPv6. For more details, see the [spec](https://github.com/libp2p/specs/tree/master/addressing).
