### ISSUE TITLE
how to encode publicKeys / other meta infromation

### ISSUE THREAD

**Issue by wanderer** [multiformats/multiaddr#12]
How would you add something like a public key? Like this?

`/ip6/<ipv6 str addr>/<tcp int port>/<pubkey>`

Also in rlpx we only have tcp. Never  udp. So can we drop the  udp/tcp identifier?
Lastly, Pubkeys are optional. How can that be expressed?

Related
 https://github.com/jbenet/multiaddr/issues/6#issuecomment-156431790

**Comment by lgierth** [comment]
I'll be in a similar situation with cjdns/fc00, and so far I thing it's fine to include the public-key in the multiaddr, if it's required for opening a session. IPFS does the same basically, by putting a fingerprint of the public key into the multiaddr.

For example:

```
/ip4/1.2.3.4/udp/54321/cjdns/<thepublickey>
```

Regarding the representation of keys, this is relevant: ipfs/specs#58
