### ISSUE TITLE
Add WebTransport

### ISSUE THREAD

**Issue by mriise** [multiformats/multiaddr#123]
Similar transport to Websocket that uses a http/3 instead. Great news for browsers as it (should) allow them to use the multiplexing and congestion control capabilities of QUIC.   

w3 draft: https://www.w3.org/TR/webtransport/
firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1692754
chrome: https://chromestatus.com/feature/4854144902889472

**Comment by Stebalien** [comment]
https://www.w3.org/TR/webtransport/#certificate-hashes :partying_face:. If this actually becomes a thing for more than just chrome, it'll solve most of our problems.
