### ISSUE TITLE
Signalling incoming/outbound connections

### ISSUE THREAD

**Issue by vmx** [multiformats/multiaddr#149]
I currently work on a prototype to allow direct browser to browser connections for peers within the same network without an intermediate server. The information on how to connect to the other peer (basically the ICE candidates) are encoded in a Multiaddress. That Multiaddress can then be used to dial the peer via libp2p.

In WebRTC you always have one peer that initiates a connection, while the other peer then connects to it. So you have two different kinds of Multiaddresses. One that will act as the peer that initiates the connection and one for the peer that accepts that connection.

I'd like to have a way to signal this. I don't think that's currently possible, would there be a way to add this to Multiaddress?

Currently I just append `/webrtc-initiator` and `/webrtc-receiver` to my addresses. But perhaps it could be more general purpose, so that it can be used outside my specific needs. Kind of similar [WebRTC TCP candidate types](https://developer.mozilla.org/en-US/docs/Web/API/WebRTC_API/Connectivity#tcp_candidate_types) that specifies whether a transport will accept incoming or outbound connections.

I could imagine this also being used when you e.g. want to allow only certain dialable addresses. Let's say my peer only wants connections from a certain peer. It could dial itself with the information of the other peer and keep track of that.

**Comment by vmx** [comment]
I've discovered the `memory` protocol, which can be (mis)used for application specific things. That works for my case. Hence I'm closing my issue.

**Comment by mxinden** [comment]
(Mis)using the `memory` transport, at least for small projects, sounds good to me.
