### ISSUE TITLE
Variable length addresses

### ISSUE THREAD

**Issue by jbenet** [multiformats/multiaddr#2]
At the moment, multiaddr only handles fixed-length addresses. If we were to add support for IPFS, it has variable length addresses (multihashes). 

Not sure exactly how multiaddr should address this. Perhaps variable length addresses can be prefixed with their byte length when in binary packed form. e.g.

```
(<1 byte proto> (<n byte addr>))+
(<1 byte proto> (<1 byte addr size (n-1)><n-1 byte addr>))+
```

**Comment by basile-henry** [comment]
I'm looking into implementing multiaddr in Haskell, to be used with the [hs-ipfs-api](https://github.com/basile-henry/hs-ipfs-api).
Is this how multiaddr should be implemented for variable length addresses? I doubt any variable length address would ever be bigger than 255 bytes, but should the size byte be a varint (like UTF8)?

Also in the case of a 0 length protocol (in the protocol table: udt, utp, http, https) how does it serialize as a string, with no '/' in between the protocol and the address?

`/ip4/0.0.0.0/tcp/80/http` vs `/ip4/0.0.0.0/tcp/80/http/`

`/ip4/0.0.0.0/tcp/80/http/<custom protocol>/<custom address>` vs
`/ip4/0.0.0.0/tcp/80/http//<custom protocol>/<custom address>`

I noticed that the js implementation has the biggest [protocol.csv](https://github.com/jbenet/js-multiaddr/blob/master/src/protocols.csv) table, is that the reference?

**Comment by lgierth** [comment]
multiaddr already supports variable-length string representations -- we split string representations on forward-slashes (`/`), and prefix values in binary representation with uvarints.
