### ISSUE TITLE
Where can i find a list off all the protocol codes?

### ISSUE THREAD

**Issue by fd** [multiformats/multiaddr#4]
Not just the ones in protocols.csv

**Comment by yalamerde** [comment]
Why not mentioning [NDN](https://hypothes.is/a/AVItYhEX8sFu_DXLVZj3) here?

@rynomad once also used telehash to route [Federated Wiki](https://github.com/fedwiki/wiki-server/issues/106) from [browser to browser](https://github.com/rynomad/CCNx-Federated-Wiki).

**Comment by lgierth** [comment]
There's a protocols.csv file in the root of this repository now, and some of the implementations have the same file, with the protocols they support.
