### ISSUE TITLE
Why?

### ISSUE THREAD

**Issue by timthelion** [multiformats/multiaddr#41]
You write of the URL standard:

````
This isn't optimal. Instead, addresses should be formatted so:
````

but you don't write WHY it isn't optiomal and WHY your new standard is better...

**Comment by lgierth** [comment]
Agreed, this aspect is very under-documented. ipfs/in-web-browsers#4 has a rough version of this, and I'm currently working on making this a proper nice document.

**Comment by lgierth** [comment]
The readme addresses this better now
