### ISSUE TITLE
1 byte binary representation vs. protocol codes > 255

### ISSUE THREAD

**Issue by keks** [multiformats/multiaddr#8]
The spec states that in the binary representation every protocol has a 1 byte code. However, there are quite some protocols defined with a number that is not representable with 1 byte.

**Comment by jbenet** [comment]
It should say varint

**Comment by basile-henry** [comment]
Which Varint format is being used? Is it [protobuf's Base 128 Varints](https://developers.google.com/protocol-buffers/docs/encoding#varints) or something like [UTF-8](https://en.wikipedia.org/wiki/UTF-8)?

**Comment by ProgVal** [comment]
Why not use 2 bytes, mapping IANA ports? This would reusing an existing map instead of creating a new one.

**Comment by jbenet** [comment]
Because that's not infinitely scalable. Need a varint.

And IANA doesn't cover all things we want to cover. I think We try to use
IANA numbers where able.
