### ISSUE TITLE
DNS name binary encoding

### ISSUE THREAD

**Issue by alexander255** [multiformats/multiaddr#94]
As mentioned in #22, `/dns`, `/dns4`, `/dns6` & `/dnsaddr` do not currently have an official binary encoding defined.

In [`py-multiaddr`](https://github.com/multiformats/py-multiaddr/blob/master/multiaddr/protocols.py#L130-L133) we currently use Unicode for the text representation and IDNA-2008/Punnycode for the binary representation. Obviously this distinction is only relevant for domains with labels containing non-ASCII characters.

How is this handled in other implementations? Is the current behaviour something that could be standardized or is another behaviour more desirable?

**Comment by Stebalien** [comment]
I believe the current de-facto standard in go and js is to just encode the unicode to utf-8. IIRC, punnycode is only _really_ needed for compatibility with the DNS protocol.

However, this may have canonization issues.

**Comment by alexander255** [comment]
> However, this may have canonization issues.

Canonicalizing domain name strings is specified by [UTS46](https://www.unicode.org/reports/tr46/#Processing). In particular that specification requires one to [ship a mapping table] and decode all domain name labels starting with `xn--`using [Punnycode](http://ietf.org/rfc/rfc3492.txt) to validate & lower-case their contents. So while could store the end result of this process as UTF-8 rather then IDNA, we'd still have to implement/ship most IDNA stuff anyways to ensure canonicalization of the generated values.

**Comment by Stebalien** [comment]
(belatedly)

I believe most DNS resolvers will do this internally. I'm fine saying that any domain in a `/dns` string must have already been converted from punycode to utf-8.

(unless I'm missing something important)

**Comment by alexander255** [comment]
@Stebalien and me went for standardizing UTF-8 encoding with UTS-46 normalization/canonicalization in #101.
